### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Jawastew** [Via-profit/js-timepicker#1]
Hi,  
I would like to use your code in one of my projects, would you be so kind as to include a license with your code?  

Kind Regards,  
Jawastew

PS: This site claims your code has a MIT License: https://www.cssscript.com/minimal-timer-picker-pure-javascript

**Comment by Via-profit** [comment]
Thank you for contacting! Yes, this is MIT Licence. We updated Readme file

**Comment by Jawastew** [comment]
Thank you!
